; Script generated by Claude
; Installer for Sound to XML Converter

; Definir constantes
!define APPNAME "Sound to XML Converter"
!define COMPANYNAME "Sound Tools"
!define DESCRIPTION "Conversor de archivos de audio a XML"
!define VERSIONMAJOR 1
!define VERSIONMINOR 0
!define VERSIONBUILD 0

; Configuraciones del instalador
SetCompressor lzma
Unicode true

; Información general
Name "${APPNAME}"
OutFile "Sound to XML Installer.exe"
InstallDir "$PROGRAMFILES\${APPNAME}"
InstallDirRegKey HKLM "Software\${APPNAME}" ""

; Solicitar privilegios de administrador
RequestExecutionLevel admin

; Páginas del instalador
!include "MUI2.nsh"
!define MUI_ABORTWARNING

; Interfaz moderna
!define MUI_ICON "assets\icon.ico"
!define MUI_UNICON "assets\icon.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "assets\installer_welcome.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "assets\installer_header.bmp"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

!insertmacro MUI_LANGUAGE "Spanish"

; Sección principal de instalación
Section "Instalar ${APPNAME}" SecMain
    SetOutPath "$INSTDIR"
    
    ; Copiar archivos del programa
    File /r "dist\Sound to XML Converter\*.*"
    
    ; Crear acceso directo en el menú inicio
    CreateDirectory "$SMPROGRAMS\${APPNAME}"
    CreateShortcut "$SMPROGRAMS\${APPNAME}\${APPNAME}.lnk" "$INSTDIR\Sound to XML Converter.exe"
    CreateShortcut "$SMPROGRAMS\${APPNAME}\Desinstalar.lnk" "$INSTDIR\uninstall.exe"
    
    ; Crear acceso directo en el escritorio
    CreateShortcut "$DESKTOP\${APPNAME}.lnk" "$INSTDIR\Sound to XML Converter.exe"
    
    ; Registrar desinstalador
    WriteUninstaller "$INSTDIR\uninstall.exe"
    
    ; Registrar información en el registro de Windows
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "DisplayName" "${APPNAME}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "UninstallString" "$\"$INSTDIR\uninstall.exe$\""
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "DisplayIcon" "$INSTDIR\Sound to XML Converter.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "Publisher" "${COMPANYNAME}"
SectionEnd

; Sección de desinstalación
Section "Uninstall"
    ; Eliminar archivos y carpetas
    RMDir /r "$INSTDIR"
    
    ; Eliminar accesos directos
    RMDir /r "$SMPROGRAMS\${APPNAME}"
    Delete "$DESKTOP\${APPNAME}.lnk"
    
    ; Eliminar registro
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}"
    DeleteRegKey HKLM "Software\${APPNAME}"
SectionEnd